services:
    latex-compiler:
        build:
            context: ./latex
            dockerfile: Dockerfile
        volumes:
            - ./fonts /app/fonts
            - ./templates /app/tempates
            - ./output:/app/output
            - latex-cache:/root/.texlive2023
        networks:
            - resume-network

volumes:
    latex-cache:
        driver: local
